ame: workflowName2

on:
  # push:
  #   branches: [ "main" ]

   workflow_dispatch:

jobs:
  jobNew:
    runs-on: ubuntu-latest

    steps:
    
    
    
    
    - uses: actions/checkout@v3
      
    - name: Run a one-line script
      run: echo this is from VS - Code and file name is task2.yml